# Publish to PyPi package index

name: PIP Publish

on:
  release:
    types: [published]

jobs:

  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check Release Tag
        run: |
          python3 ci/check_version_number.py ${{ github.event.release.tag_name }}
      - name: Install Python Dependencies
        run: |
          pip install -U -r requirements.txt
          pip install --upgrade wheel setuptools twine build
      - name: Build Binary
        run: |
          python3 -m build
      - name: Publish
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
  